var annotated_dup =
[
    [ "ibex_alu", "moduleibex__alu.html", "moduleibex__alu" ],
    [ "ibex_branch_predict", "moduleibex__branch__predict.html", "moduleibex__branch__predict" ],
    [ "ibex_compressed_decoder", "moduleibex__compressed__decoder.html", "moduleibex__compressed__decoder" ],
    [ "ibex_controller", "moduleibex__controller.html", "moduleibex__controller" ],
    [ "ibex_core", "moduleibex__core.html", "moduleibex__core" ],
    [ "ibex_counter", "moduleibex__counter.html", "moduleibex__counter" ],
    [ "ibex_cs_registers", "moduleibex__cs__registers.html", "moduleibex__cs__registers" ],
    [ "ibex_csr", "moduleibex__csr.html", "moduleibex__csr" ],
    [ "ibex_decoder", "moduleibex__decoder.html", "moduleibex__decoder" ],
    [ "ibex_dummy_instr", "moduleibex__dummy__instr.html", "moduleibex__dummy__instr" ],
    [ "ibex_ex_block", "moduleibex__ex__block.html", "moduleibex__ex__block" ],
    [ "ibex_fetch_fifo", "moduleibex__fetch__fifo.html", "moduleibex__fetch__fifo" ],
    [ "ibex_icache", "moduleibex__icache.html", "moduleibex__icache" ],
    [ "ibex_id_stage", "moduleibex__id__stage.html", "moduleibex__id__stage" ],
    [ "ibex_if_stage", "moduleibex__if__stage.html", "moduleibex__if__stage" ],
    [ "ibex_load_store_unit", "moduleibex__load__store__unit.html", "moduleibex__load__store__unit" ],
    [ "ibex_lockstep", "moduleibex__lockstep.html", "moduleibex__lockstep" ],
    [ "ibex_multdiv_fast", "moduleibex__multdiv__fast.html", "moduleibex__multdiv__fast" ],
    [ "ibex_multdiv_slow", "moduleibex__multdiv__slow.html", "moduleibex__multdiv__slow" ],
    [ "ibex_pkg", "packageibex__pkg.html", "packageibex__pkg" ],
    [ "ibex_pmp", "moduleibex__pmp.html", "moduleibex__pmp" ],
    [ "ibex_prefetch_buffer", "moduleibex__prefetch__buffer.html", "moduleibex__prefetch__buffer" ],
    [ "ibex_register_file_ff", "moduleibex__register__file__ff.html", "moduleibex__register__file__ff" ],
    [ "ibex_register_file_fpga", "moduleibex__register__file__fpga.html", "moduleibex__register__file__fpga" ],
    [ "ibex_register_file_latch", "moduleibex__register__file__latch.html", "moduleibex__register__file__latch" ],
    [ "ibex_top", "moduleibex__top.html", "moduleibex__top" ],
    [ "ibex_top_tracing", "moduleibex__top__tracing.html", "moduleibex__top__tracing" ],
    [ "ibex_tracer", "moduleibex__tracer.html", "moduleibex__tracer" ],
    [ "ibex_tracer_pkg", "packageibex__tracer__pkg.html", "packageibex__tracer__pkg" ],
    [ "ibex_wb_stage", "moduleibex__wb__stage.html", "moduleibex__wb__stage" ]
];